"""added no of faq

Revision ID: 0266f9f7743a
Revises: a6091775f7b1
Create Date: 2026-07-03 15:21:45.427747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0266f9f7743a'
down_revision: Union[str, Sequence[str], None] = 'a6091775f7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('no_of_faqs', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('no_of_reviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'no_of_reviews')
    op.drop_column('products', 'no_of_faqs')
    # ### end Alembic commands ###
