"""added country

Revision ID: 0aabde4e93b8
Revises: 9bf9b488ac06
Create Date: 2026-09-18 07:29:57.158490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aabde4e93b8'
down_revision: Union[str, Sequence[str], None] = '9bf9b488ac06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_users', sa.Column('country', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_users', 'country')
    # ### end Alembic commands ###
