"""added brand analytics

Revision ID: 2885b10ad531
Revises: c00b03d1a756
Create Date: 2026-08-05 07:38:42.200330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2885b10ad531"
down_revision: Union[str, Sequence[str], None] = "c00b03d1a756"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_analytics",
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("sentiment", sa.String(), nullable=True),
        sa.Column(
            "model_choice",
            postgresql.ENUM(
                "GPT", "GEMINI", "CLAUDE", name="llmmodels", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("mention_score", sa.Float(), nullable=True),
        sa.Column("citation_score", sa.Float(), nullable=True),
        sa.Column("share_of_voice_score", sa.Float(), nullable=True),
        sa.Column("product_coverage_score", sa.Float(), nullable=True),
        sa.Column("category_coverage_score", sa.Float(), nullable=True),
        sa.Column("knowledge_graph_score", sa.Float(), nullable=True),
        sa.Column("authority_score", sa.Float(), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("diagnosis", sa.JSON(), nullable=True),
        sa.Column("recommendations", sa.JSON(), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=True),
        sa.Column("competitors", sa.JSON(), nullable=True),
        sa.Column("generated_prompts", sa.JSON(), nullable=True),
        sa.Column("prompt_factory", sa.JSON(), nullable=True),
        sa.Column("dimensions", sa.JSON(), nullable=True),
        sa.Column("share_of_voice_value", sa.Float(), nullable=True),
        sa.Column("share_of_voice_raw_response", sa.JSON(), nullable=True),
        sa.Column("product_coverage_value", sa.Float(), nullable=True),
        sa.Column("product_coverage_raw_response", sa.JSON(), nullable=True),
        sa.Column("category_coverage_value", sa.Float(), nullable=True),
        sa.Column("category_coverage_raw_response", sa.JSON(), nullable=True),
        sa.Column("knowledge_graph_value", sa.Float(), nullable=True),
        sa.Column("knowledge_graph_raw_response", sa.JSON(), nullable=True),
        sa.Column("authority_value", sa.Float(), nullable=True),
        sa.Column("authority_raw_response", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("brand_analytics")
    # ### end Alembic commands ###
