"""added query optimization tag

Revision ID: 4c41ee6bd1c0
Revises: 58189356054f
Create Date: 2026-07-16 06:14:49.142743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c41ee6bd1c0'
down_revision: Union[str, Sequence[str], None] = '58189356054f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_search_queries', sa.Column('query_optimization_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_search_queries', 'query_optimization_tag')
    # ### end Alembic commands ###
