"""initial app settings

Revision ID: 58189356054f
Revises: e8ab810fe981
Create Date: 2026-07-14 05:40:51.011267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58189356054f'
down_revision: Union[str, Sequence[str], None] = 'e8ab810fe981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appsettings',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sa.Text(), nullable=True),
    sa.Column('anthropic_api_key', sa.Text(), nullable=True),
    sa.Column('google_api_key', sa.Text(), nullable=True),
    sa.Column('groq_api_key', sa.Text(), nullable=True),
    sa.Column('deepseek_api_key', sa.Text(), nullable=True),
    sa.Column('perplexity_api_key', sa.Text(), nullable=True),
    sa.Column('xai_api_key', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appsettings')
    # ### end Alembic commands ###
