"""added actual content item

Revision ID: 918f8a5f8b70
Revises: c67535ade94f
Create Date: 2026-09-15 09:14:33.273808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '918f8a5f8b70'
down_revision: Union[str, Sequence[str], None] = 'c67535ade94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE chats SET input_tokens = 0 WHERE input_tokens IS NULL")
    op.execute("UPDATE chats SET output_tokens = 0 WHERE output_tokens IS NULL")
    op.execute("UPDATE chats SET total_tokens = 0 WHERE total_tokens IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('products', sa.Column('actual_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('extraction_token_usage', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'extraction_token_usage')
    op.drop_column('products', 'actual_content')
    op.alter_column('chats', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
