"""added competitor products

Revision ID: 9a462eb43b6c
Revises: 4c41ee6bd1c0
Create Date: 2026-07-30 06:25:07.079848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a462eb43b6c"
down_revision: Union[str, Sequence[str], None] = "4c41ee6bd1c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_search_queries",
        sa.Column(
            "competitor_products",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_search_queries", "competitor_products")
    # ### end Alembic commands ###
