"""added competitor in brand

Revision ID: a0cc3060a757
Revises: f18f09d53c50
Create Date: 2026-06-26 14:26:17.394633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0cc3060a757'
down_revision: Union[str, Sequence[str], None] = 'f18f09d53c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('competitor', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'competitor')
    # ### end Alembic commands ###
