"""add projects

Revision ID: a6091775f7b1
Revises: a0cc3060a757
Create Date: 2026-07-02 13:49:24.883410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6091775f7b1'
down_revision: Union[str, Sequence[str], None] = 'a0cc3060a757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('website_url', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('countries', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'countries')
    op.drop_column('tenants', 'description')
    op.drop_column('tenants', 'website_url')
    op.drop_column('tenants', 'industry')
    # ### end Alembic commands ###
