"""added integers

Revision ID: aa99fc1fe2ea
Revises: 2885b10ad531
Create Date: 2026-09-03 15:12:49.648904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa99fc1fe2ea'
down_revision: Union[str, Sequence[str], None] = '2885b10ad531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_name_ai', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('products', sa.Column('features_ai', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('products', sa.Column('current_ai_features', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('products', sa.Column('description_ai', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('products', sa.Column('ai_title_rewrite_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('ai_features_rewrite_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('ai_description_rewrite_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ai_description_rewrite_count')
    op.drop_column('products', 'ai_features_rewrite_count')
    op.drop_column('products', 'ai_title_rewrite_count')
    op.drop_column('products', 'description_ai')
    op.drop_column('products', 'current_ai_features')
    op.drop_column('products', 'features_ai')
    op.drop_column('products', 'product_name_ai')
    # ### end Alembic commands ###
