"""added singlerecommandation

Revision ID: b1a4dd56ff1b
Revises: 0aabde4e93b8
Create Date: 2026-09-21 09:26:49.058596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1a4dd56ff1b'
down_revision: Union[str, Sequence[str], None] = '0aabde4e93b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('single_recommandation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'single_recommandation')
    # ### end Alembic commands ###
