"""added solutin field

Revision ID: c00b03d1a756
Revises: 9a462eb43b6c
Create Date: 2026-07-30 11:17:10.873808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00b03d1a756'
down_revision: Union[str, Sequence[str], None] = '9a462eb43b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_search_queries', sa.Column('solution', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_search_queries', 'solution')
    # ### end Alembic commands ###
