"""citations

Revision ID: c67535ade94f
Revises: aa99fc1fe2ea
Create Date: 2026-09-11 06:22:44.537799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c67535ade94f'
down_revision: Union[str, Sequence[str], None] = 'aa99fc1fe2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chats', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'total_tokens')
    op.drop_column('chats', 'output_tokens')
    op.drop_column('chats', 'input_tokens')
    op.drop_column('chats', 'citations')
    # ### end Alembic commands ###
