"""chat initial

Revision ID: f18f09d53c50
Revises: 33091dc2d0cf
Create Date: 2026-06-26 11:14:49.570933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f18f09d53c50'
down_revision: Union[str, Sequence[str], None] = '33091dc2d0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_url', sa.String(length=512), nullable=False),
    sa.Column('extra_context', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('final_optimization_report', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_search_queries',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(length=512), nullable=False),
    sa.Column('product_found', sa.Boolean(), nullable=False),
    sa.Column('share_of_voice', sa.Float(), nullable=False),
    sa.Column('total_websites_found', sa.Integer(), nullable=False),
    sa.Column('citation_rank', sa.Integer(), nullable=False),
    sa.Column('platform_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('best_metrics_variance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_api_response', sa.String(), nullable=False),
    sa.Column('citing_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitors_mentioned', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_optimization_tips', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_search_queries')
    op.drop_table('chats')
    # ### end Alembic commands ###
